/**
 * SUTRADARA AJAIB ASY & SYIFA ENGINE — SPRINT G22
 * 
 * Penanda: G22_SUTRADARA_AJAIB_VERIFIED
 * 
 * Automatic offline deterministic story director engine that composes complete
 * interactive cartoon episodes, scene structures, character choreography,
 * camera paths (G21), sound effects (G20), and outputs to TV Asy, Buku Cerita,
 * Festival, and Asset Center without any paid AI dependencies.
 */

import { blackBoxRecorder } from './blackBoxRecorder';
import { magicCameraEngine, CameraMotion, SceneEntrance, SceneExit } from './magicCameraEngine';
import { asySyifaDnaEngine, DnaSignatureSound, MovementStyle, OfficialExpression } from './asySyifaDnaEngine';
import { CharacterType } from '../components/mascot/CartoonCharacterSvg';
import { tadeAnimationGovernor } from './tadeAnimationGovernor';

export type DirectorTheme = 
  | 'PPDB'
  | 'RAMADHAN'
  | 'WISUDA'
  | 'MILAD'
  | 'TRANSPORTASI'
  | 'HEWAN'
  | 'PROFESI'
  | 'ALAM'
  | 'PERSAHABATAN'
  | 'ADAB';

export type DirectorLocation = 
  | 'RUMAH_ASY'
  | 'KAMPUNG_CERIA'
  | 'FESTIVAL'
  | 'MASJID'
  | 'TAMAN'
  | 'STASIUN'
  | 'PASAR_CERIA';

export interface DirectorSceneFrame {
  id: string;
  sequence: number;
  location: DirectorLocation;
  locationLabel: string;
  leadCharacter: CharacterType;
  companionCharacters: Array<{
    type: CharacterType;
    movement: MovementStyle;
    expression: OfficialExpression;
    actionDescription: string;
  }>;
  leadMovement: MovementStyle;
  leadExpression: OfficialExpression;
  dialogueSpeaker: string;
  dialogueText: string;
  narrationText: string;
  cameraMotion: CameraMotion;
  entranceEffect: SceneEntrance;
  exitEffect: SceneExit;
  soundFx: DnaSignatureSound;
  soundCueLabel: string;
  moralLesson: string;
  duaPhrase: string;
  bgGradient: string;
  ambientEmoji: string[];
}

export interface DirectedEpisode {
  id: string;
  code: string;
  theme: DirectorTheme;
  title: string;
  subtitle: string;
  targetAudience: string;
  estimatedDurationSec: number;
  location: DirectorLocation;
  leadCast: CharacterType[];
  frames: DirectorSceneFrame[];
  fullMoralValue: string;
  featuredDua: string;
  badgeEmoji: string;
  createdAt: number;
  isDailyAutoGenerated: boolean;
  exportedTargets: Array<'TV_ASY' | 'BUKU_CERITA' | 'FESTIVAL' | 'PUSAT_ASET'>;
  status: 'DRAFT' | 'APPROVED' | 'PUBLISHED';
}

export interface DirectorConfig {
  dailyAutoDirectorEnabled: boolean;
  lastDailyDateStr: string;
  defaultSceneCount: number;
  preferredSpeed: 'LEMBUT' | 'STANDAR' | 'RINGKAS';
  highPerformanceGpu: boolean;
  autoSyncToTvAsy: boolean;
  autoSyncToBukuCerita: boolean;
}

const STORAGE_KEY_DIRECTOR_CONFIG = 'tade_g22_sutradara_config_v1';
const STORAGE_KEY_DIRECTED_EPISODES = 'tade_g22_directed_episodes_v1';

export const THEME_METADATA: Record<DirectorTheme, {
  name: string;
  badge: string;
  icon: string;
  color: string;
  defaultLocation: DirectorLocation;
  defaultLead: CharacterType;
  description: string;
  moralCore: string;
  duaCore: string;
}> = {
  PPDB: {
    name: 'Sambut Sahabat Baru (PPDB)',
    badge: '🏫 Penerimaan Sahabat Baru',
    icon: '🎒',
    color: 'from-sky-500 to-emerald-600',
    defaultLocation: 'RUMAH_ASY',
    defaultLead: 'ASY',
    description: 'Menyambut adik-adik baru di TK Asy Syifa dengan senyuman hangat, keliling kelas ceria, dan doa belajar.',
    moralCore: 'Ramah dan senang membantu sahabat baru yang pertama kali ke sekolah.',
    duaCore: 'Rabbi zidni \'ilman warzuqni fahman (Ya Allah tambahkanlah ilmuku dan karuniakanlah pemahaman)'
  },
  RAMADHAN: {
    name: 'Gembira Ramadhan & Idul Fitri',
    badge: '🌙 Bulan Berkah & Sedekah',
    icon: '🕌',
    color: 'from-emerald-600 to-teal-700',
    defaultLocation: 'MASJID',
    defaultLead: 'SYIFA',
    description: 'Syifa menyalakan lentera Ramadhan, sahur bersama, belajar berbagi takjil, dan sholat tarawih berjamaah.',
    moralCore: 'Belajar berpuasa dengan gembira, memperbanyak sedekah dan menyayangi sesama.',
    duaCore: 'Dzahabadzh zhama-u wabtallatil \'uruuqu wa tsabatal ajru in syaa Allah'
  },
  WISUDA: {
    name: 'Wisuda Akbar & Pelepasan Sahabat',
    badge: '🎓 Langkah Awal Berprestasi',
    icon: '📜',
    color: 'from-indigo-600 to-purple-700',
    defaultLocation: 'FESTIVAL',
    defaultLead: 'DUO' as unknown as CharacterType,
    description: 'Momen penuh rasa syukur, persembahan lagu hafalan Qur\'an, sungkem takzim kepada guru dan orang tua.',
    moralCore: 'Bersyukur atas ilmu yang didapat dan terus berakhlak mulia di jenjang berikutnya.',
    duaCore: 'Alhamdulillahilladzi bini\'matihi tatimmus shaalihaat'
  },
  MILAD: {
    name: 'Milad Yayasan & Sekolah Asy Syifa',
    badge: '🎂 Syukur & Karnaval Ceria',
    icon: '🎈',
    color: 'from-amber-500 to-rose-600',
    defaultLocation: 'FESTIVAL',
    defaultLead: 'ASY',
    description: 'Pawai karnaval pakaian adat anak sholeh, stan karya seni, pembagian bingkisan berkah, dan tumpeng syukur.',
    moralCore: 'Mencintai sekolah dan bersama-sama merawat taman serta lingkungan belajar.',
    duaCore: 'Barakallahu fiikum wa jazzakumullahu khairan'
  },
  TRANSPORTASI: {
    name: 'Petualangan Kereta & Transportasi Ceria',
    badge: '🚂 Naik Kereta Cerita & Tertib',
    icon: '🚆',
    color: 'from-cyan-600 to-blue-700',
    defaultLocation: 'STASIUN',
    defaultLead: 'ASY',
    description: 'Dek Asy menjadi masinis cilik bersahabat, Bubu memeriksa karcis dengan senyum, dan Gogo melambaikan bendera hijau aman.',
    moralCore: 'Tertib antre, membaca doa naik kendaraan, dan menghormati petugas keselamatan.',
    duaCore: 'Subhaanal ladzii sakh-khara lanaa haadzaa wa maa kunnaa lahu muqriniin'
  },
  HEWAN: {
    name: 'Menyayangi Hewan Ciptaan Allah',
    badge: '🐑 Sahabat Alam & Satwa',
    icon: '🐾',
    color: 'from-emerald-500 to-amber-600',
    defaultLocation: 'TAMAN',
    defaultLead: 'SYIFA',
    description: 'Memberi makan kucing lucu di taman, mendengar kicauan burung pagi, dan merawat kelinci dengan penuh kasih.',
    moralCore: 'Kasih sayang kepada semua makhluk hidup adalah pintu datangnya rahmat Allah.',
    duaCore: 'Irhamuu man fil ardhi yarhamkum man fis samaa-i (Sayangilah yang di bumi, niscaya yang di langit menyayangimu)'
  },
  PROFESI: {
    name: 'Cita-Cita Hebat & Profesi Mulia',
    badge: '🩺 Dokter, Guru & Masinis Cilik',
    icon: '👨‍⚕️',
    color: 'from-blue-600 to-indigo-700',
    defaultLocation: 'KAMPUNG_CERIA',
    defaultLead: 'ASY',
    description: 'Mengenal tugas dokter cilik mengobati teman, guru yang sabar mengajar, dan petani yang menanam padi berkah.',
    moralCore: 'Bekerja dengan jujur, ikhlas menolong, dan bersungguh-sungguh menggapai cita-cita.',
    duaCore: 'Allahumma inni as-aluka \'ilman nafi\'an wa rizqan thayyiban wa \'amalan mutaqabbala'
  },
  ALAM: {
    name: 'Kebun Asri & Menjaga Alam',
    badge: '🌱 Menanam Pohon & Bersih Sungai',
    icon: '🌳',
    color: 'from-emerald-600 to-green-800',
    defaultLocation: 'KAMPUNG_CERIA',
    defaultLead: 'SYIFA',
    description: 'Menanam bibit bunga dan pohon buah di kebun, memilah sampah daun, dan menikmati semilir angin segar.',
    moralCore: 'Bumi adalah titipan Allah yang wajib dijaga kebersihan dan keasriannya.',
    duaCore: 'Maa min muslimin yagh-risu gharsan illa kaana lahu shadaqah (Setiap muslim yang menanam pohon bernilai sedekah)'
  },
  PERSAHABATAN: {
    name: 'Indahnya Berbagi & Persahabatan',
    badge: '🤝 Sahabat Sejati Saling Menolong',
    icon: '💖',
    color: 'from-rose-500 to-amber-500',
    defaultLocation: 'PASAR_CERIA',
    defaultLead: 'ASY',
    description: 'Berbagi bekal kue sehat, meminjamkan pensil warna saat menggambar, dan saling memaafkan jika ada perselisihan.',
    moralCore: 'Persaudaraan yang tulus karena Allah membuat hati selalu damai dan bahagia.',
    duaCore: 'Al-mu\'minu lil mu\'mini kal bunyaani yasyuddu ba\'dhuhu ba\'dha (Mukmin satu dengan yang lain bagaikan bangunan kokoh)'
  },
  ADAB: {
    name: 'Adab Santun & Akhlakul Karimah',
    badge: '✨ Senyum, Salam, Sapa & Doa',
    icon: '🤲',
    color: 'from-teal-600 to-emerald-700',
    defaultLocation: 'RUMAH_ASY',
    defaultLead: 'SYIFA',
    description: 'Membiasakan 5S (Senyum, Salam, Sapa, Sopan, Santun), makan duduk dengan tangan kanan, dan berterima kasih.',
    moralCore: 'Akhlak yang baik adalah amalan paling berat timbangannya di hari kiamat.',
    duaCore: 'Allahumma ahsanta khalqii fa ahsin khuluqii (Ya Allah sebagaimana Kau baguskan rupaku, baguskanlah pula akhlakku)'
  }
};

export const LOCATION_METADATA: Record<DirectorLocation, {
  name: string;
  bgGradient: string;
  ambientEmoji: string[];
  signatureSound: DnaSignatureSound;
}> = {
  RUMAH_ASY: {
    name: 'Rumah Asy Syifa & Ruang Belajar',
    bgGradient: 'from-amber-100 via-emerald-50 to-teal-100',
    ambientEmoji: ['🏡', '📚', '☀️', '🌸', '🪑'],
    signatureSound: 'FLIP_BUKU'
  },
  KAMPUNG_CERIA: {
    name: 'Kampung Ceria & Balai Warga',
    bgGradient: 'from-sky-100 via-emerald-100 to-yellow-100',
    ambientEmoji: ['🌳', '🚲', '🌻', '🏡', '🎈'],
    signatureSound: 'TEPUK_TANGAN_KECIL'
  },
  FESTIVAL: {
    name: 'Panggung Karnaval & Lapangan Seni',
    bgGradient: 'from-amber-100 via-rose-100 to-indigo-100',
    ambientEmoji: ['🎪', '🎈', '🎊', '⭐', '🍭'],
    signatureSound: 'POP_BALON'
  },
  MASJID: {
    name: 'Masjid Taman Syurga Ceria',
    bgGradient: 'from-emerald-100 via-teal-100 to-sky-100',
    ambientEmoji: ['🕌', '🌙', '✨', '📿', '🕊️'],
    signatureSound: 'PLING_BINTANG'
  },
  TAMAN: {
    name: 'Taman Bermain Bunga & Satwa Ceria',
    bgGradient: 'from-green-100 via-emerald-50 to-sky-100',
    ambientEmoji: ['🌳', '🦋', '🌷', '🐿️', '🌈'],
    signatureSound: 'PLING_BINTANG'
  },
  STASIUN: {
    name: 'Stasiun Kereta Cerita & Rel Pelangi',
    bgGradient: 'from-sky-200 via-blue-100 to-emerald-100',
    ambientEmoji: ['🚂', '🚦', '🛤️', '🎫', '☁️'],
    signatureSound: 'POP_BALON'
  },
  PASAR_CERIA: {
    name: 'Pasar Ceria Buah & Kue Sehat',
    bgGradient: 'from-orange-100 via-amber-50 to-emerald-100',
    ambientEmoji: ['🧺', '🍎', '🍉', '🍞', '🛍️'],
    signatureSound: 'TEPUK_TANGAN_KECIL'
  }
};

class SutradaraAjaibEngine {
  private config: DirectorConfig = {
    dailyAutoDirectorEnabled: true,
    lastDailyDateStr: '',
    defaultSceneCount: 3,
    preferredSpeed: 'STANDAR',
    highPerformanceGpu: true,
    autoSyncToTvAsy: true,
    autoSyncToBukuCerita: true
  };

  private episodes: DirectedEpisode[] = [];
  private listeners: Array<(episodes: DirectedEpisode[]) => void> = [];
  private configListeners: Array<(config: DirectorConfig) => void> = [];

  constructor() {
    this.loadFromStorage();
    this.seedDefaultEpisodesIfEmpty();
    this.checkDailyAutoGeneration();
  }

  private loadFromStorage() {
    try {
      if (typeof window !== 'undefined' && window.localStorage) {
        const savedCfg = localStorage.getItem(STORAGE_KEY_DIRECTOR_CONFIG);
        if (savedCfg) {
          this.config = { ...this.config, ...JSON.parse(savedCfg) };
        }

        const savedEps = localStorage.getItem(STORAGE_KEY_DIRECTED_EPISODES);
        if (savedEps) {
          this.episodes = JSON.parse(savedEps);
        }
      }
    } catch {
      // safe fallback
    }
  }

  private saveToStorage() {
    try {
      if (typeof window !== 'undefined' && window.localStorage) {
        localStorage.setItem(STORAGE_KEY_DIRECTOR_CONFIG, JSON.stringify(this.config));
        localStorage.setItem(STORAGE_KEY_DIRECTED_EPISODES, JSON.stringify(this.episodes.slice(0, 40)));
      }
    } catch {
      // safe fallback
    }
  }

  private seedDefaultEpisodesIfEmpty() {
    if (this.episodes.length === 0) {
      // Seed 3 starter rich directed episodes
      const ep1 = this.composeEpisode('TRANSPORTASI', {
        titleOverride: 'Masinis Asy & Kereta Pelangi Ceria',
        customLocation: 'STASIUN'
      });
      const ep2 = this.composeEpisode('RAMADHAN', {
        titleOverride: 'Lentera Berkah Mbak Syifa & Sahur Ceria',
        customLocation: 'MASJID'
      });
      const ep3 = this.composeEpisode('PPDB', {
        titleOverride: 'Selamat Datang Sahabat Cilik di Asy Syifa',
        customLocation: 'RUMAH_ASY'
      });

      this.episodes = [ep1, ep2, ep3];
      this.saveToStorage();
    }
  }

  /**
   * P1 to P5: Deterministic Story Composer
   * Assembles characters, locations, cameras, sounds, and dialogs matching the theme.
   */
  public composeEpisode(
    theme: DirectorTheme,
    options?: {
      titleOverride?: string;
      customLocation?: DirectorLocation;
      customLead?: CharacterType;
      sceneCount?: number;
      isDaily?: boolean;
    }
  ): DirectedEpisode {
    const meta = THEME_METADATA[theme];
    const locKey = options?.customLocation || meta.defaultLocation;
    const locMeta = LOCATION_METADATA[locKey];
    const leadCast = options?.customLead || (theme === 'RAMADHAN' || theme === 'HEWAN' || theme === 'ADAB' ? 'SYIFA' : 'ASY');
    const now = Date.now();
    const episodeCode = `G22-${theme.slice(0, 3)}-${Math.floor(100 + Math.random() * 900)}`;

    const title = options?.titleOverride || `Kisah Ceria: ${meta.name}`;
    const subtitle = meta.badge;

    // Build 3 dynamic progressive frames (Pembuka, Inti Petualangan, Hikmah & Doa)
    const frames: DirectorSceneFrame[] = [];

    // Frame 1: Pembukaan Adegan
    frames.push({
      id: `${episodeCode}-F1`,
      sequence: 1,
      location: locKey,
      locationLabel: locMeta.name,
      leadCharacter: leadCast,
      companionCharacters: [
        {
          type: leadCast === 'ASY' ? 'SYIFA' : 'ASY',
          movement: 'LAMBAIAN_TANGAN',
          expression: 'SENYUM',
          actionDescription: 'Menyapa sahabat ceria dengan gembira'
        }
      ],
      leadMovement: 'LANGKAH_KECIL',
      leadExpression: 'SENYUM',
      dialogueSpeaker: leadCast === 'ASY' ? 'Dek Asy' : 'Mbak Syifa',
      dialogueText: leadCast === 'ASY' 
        ? `Assalamu'alaikum kawan-kawan! Hari ini kita belajar tema ${meta.name} di ${locMeta.name}!`
        : `Bismillah, mari kita sambut hari penuh berkah dengan tema ${meta.name}!`,
      narrationText: `Suasana di ${locMeta.name} terasa sangat hangat dan asri. Dek Asy dan Mbak Syifa bersiap memulai kisah.`,
      cameraMotion: 'MENDEKAT',
      entranceEffect: 'PELANGI_MUNCUL',
      exitEffect: 'BINTANG_KECIL',
      soundFx: locMeta.signatureSound,
      soundCueLabel: 'Suara Pembuka Ceria',
      moralLesson: meta.moralCore,
      duaPhrase: meta.duaCore,
      bgGradient: locMeta.bgGradient,
      ambientEmoji: locMeta.ambientEmoji
    });

    // Frame 2: Inti Cerita & Aksi Karakter (P2 Context Matching)
    let f2LeadMovement: MovementStyle = 'ANGGUKAN_KEPALA';
    let f2LeadExpression: OfficialExpression = 'BANGGA';
    let f2CameraMotion: CameraMotion = 'GESER_PELAN';
    let f2SoundFx: DnaSignatureSound = 'TEPUK_TANGAN_KECIL';
    let f2Dialogue = '';

    if (theme === 'TRANSPORTASI') {
      f2LeadMovement = 'LANGKAH_KECIL';
      f2LeadExpression = 'TERTAWA';
      f2CameraMotion = 'GESER_PELAN';
      f2SoundFx = 'POP_BALON';
      f2Dialogue = '“Semua penumpang sudah siap? Jangan lupa baca doa naik kendaraan ya, tut-tut berangkat!”';
    } else if (theme === 'RAMADHAN') {
      f2LeadMovement = 'LAMBAIAN_TANGAN';
      f2LeadExpression = 'SENYUM';
      f2CameraMotion = 'FOKUS_SYIFA';
      f2SoundFx = 'PLING_BINTANG';
      f2Dialogue = '“Mbak Syifa menyalakan lentera Ramadhan. Mari kita siapkan sedekah takjil untuk jamaah masjid!”';
    } else if (theme === 'PPDB') {
      f2LeadMovement = 'LANGKAH_KECIL';
      f2LeadExpression = 'BANGGA';
      f2CameraMotion = 'FOKUS_ASY';
      f2SoundFx = 'FLIP_BUKU';
      f2Dialogue = '“Ini ruang kelas kita yang indah, ada rak buku cerita, mainan edukasi, dan teman-teman yang ramah!”';
    } else {
      f2LeadMovement = 'ANGGUKAN_KEPALA';
      f2LeadExpression = 'BANGGA';
      f2CameraMotion = 'MENDEKAT';
      f2SoundFx = 'TEPUK_TANGAN_KECIL';
      f2Dialogue = `“Bersama-sama kita jalankan kebaikan ini dengan hati yang ikhlas dan saling menyayangi!”`;
    }

    frames.push({
      id: `${episodeCode}-F2`,
      sequence: 2,
      location: locKey,
      locationLabel: locMeta.name,
      leadCharacter: leadCast,
      companionCharacters: [
        {
          type: leadCast === 'ASY' ? 'SYIFA' : 'ASY',
          movement: 'ANGGUKAN_KEPALA',
          expression: 'TERTAWA',
          actionDescription: 'Mendukung dan memberi semangat'
        }
      ],
      leadMovement: f2LeadMovement,
      leadExpression: f2LeadExpression,
      dialogueSpeaker: leadCast === 'ASY' ? 'Dek Asy' : 'Mbak Syifa',
      dialogueText: f2Dialogue,
      narrationText: `Semua sahabat di ${locMeta.name} bergembira mempraktikkan akhlak terpuji dan ketertiban.`,
      cameraMotion: f2CameraMotion,
      entranceEffect: 'AWAN_BERGESER',
      exitEffect: 'CONFETTI_LEMBUT',
      soundFx: f2SoundFx,
      soundCueLabel: 'Suara Aksi Utama',
      moralLesson: meta.moralCore,
      duaPhrase: meta.duaCore,
      bgGradient: locMeta.bgGradient,
      ambientEmoji: locMeta.ambientEmoji
    });

    // Frame 3: Penutup, Hikmah & Doa Bersama
    frames.push({
      id: `${episodeCode}-F3`,
      sequence: 3,
      location: locKey,
      locationLabel: locMeta.name,
      leadCharacter: leadCast === 'ASY' ? 'SYIFA' : 'ASY',
      companionCharacters: [
        {
          type: leadCast,
          movement: 'LAMBAIAN_TANGAN',
          expression: 'TERIMA_KASIH',
          actionDescription: 'Melambaikan tangan tanda pamit santun'
        }
      ],
      leadMovement: 'LAMBAIAN_TANGAN',
      leadExpression: 'TERIMA_KASIH',
      dialogueSpeaker: leadCast === 'ASY' ? 'Mbak Syifa' : 'Dek Asy',
      dialogueText: `Alhamdulillah! Semoga kisah ${meta.name} ini bermanfaat untuk kita semua. Mari berdoa bersama!`,
      narrationText: `Dek Asy dan Mbak Syifa mengucapkan rasa syukur dan mendoakan seluruh sahabat anak sholeh.`,
      cameraMotion: 'MENJAUH',
      entranceEffect: 'DAUN_MEMBUKA',
      exitEffect: 'LAMBAIAN_ASY_SYIFA',
      soundFx: 'PLING_BINTANG',
      soundCueLabel: 'Suara Doa Berkah',
      moralLesson: meta.moralCore,
      duaPhrase: meta.duaCore,
      bgGradient: locMeta.bgGradient,
      ambientEmoji: locMeta.ambientEmoji
    });

    const newEpisode: DirectedEpisode = {
      id: `dir-ep-${now.toString(36)}`,
      code: episodeCode,
      theme,
      title,
      subtitle,
      targetAudience: 'Anak Usia Dini & Guru TK',
      estimatedDurationSec: 90,
      location: locKey,
      leadCast: [leadCast, leadCast === 'ASY' ? 'SYIFA' : 'ASY'],
      frames,
      fullMoralValue: meta.moralCore,
      featuredDua: meta.duaCore,
      badgeEmoji: meta.icon,
      createdAt: now,
      isDailyAutoGenerated: options?.isDaily || false,
      exportedTargets: ['TV_ASY', 'BUKU_CERITA'],
      status: 'APPROVED'
    };

    // Auto capture to magic camera photo memory (G21)
    magicCameraEngine.captureStoryPhoto({
      title: newEpisode.title,
      subtitle: `Sutradara Ajaib: ${meta.badge}`,
      sourceModule: 'CREATIVE_STUDIO',
      characterRole: 'DUO',
      moralLesson: newEpisode.fullMoralValue,
      duaPhrase: newEpisode.featuredDua,
      badgeEmoji: newEpisode.badgeEmoji
    });

    // Record telemetry in BlackBox
    blackBoxRecorder.record({
      moduleCode: 'SUTRADARA_AJAIB',
      role: 'GURU',
      tenant: 'TK_ASY_SYIFA',
      category: 'ACTION',
      eventType: 'ACTION',
      details: `[G22_SUTRADARA_AJAIB_VERIFIED] Episode Disusun: "${newEpisode.title}" (${newEpisode.code}) | Tema: ${theme} | Lokasi: ${locKey}`,
      route: '/director/composer',
      severity: 'INFO'
    });

    return newEpisode;
  }

  /**
   * Save, Update or Publish Directed Episode
   */
  public saveEpisode(episode: DirectedEpisode) {
    const existingIdx = this.episodes.findIndex(e => e.id === episode.id);
    if (existingIdx >= 0) {
      this.episodes[existingIdx] = episode;
    } else {
      this.episodes = [episode, ...this.episodes.slice(0, 39)];
    }
    this.saveToStorage();
    this.notifyListeners();
  }

  public deleteEpisode(id: string) {
    this.episodes = this.episodes.filter(e => e.id !== id);
    this.saveToStorage();
    this.notifyListeners();
  }

  public getEpisodes(): DirectedEpisode[] {
    return [...this.episodes];
  }

  public getEpisodeById(id: string): DirectedEpisode | undefined {
    return this.episodes.find(e => e.id === id);
  }

  public getConfig(): DirectorConfig {
    return { ...this.config };
  }

  public updateConfig(partial: Partial<DirectorConfig>) {
    this.config = { ...this.config, ...partial };
    this.saveToStorage();
    this.notifyConfigListeners();

    blackBoxRecorder.record({
      moduleCode: 'SUTRADARA_CONFIG',
      role: 'FOUNDER',
      tenant: 'TK_ASY_SYIFA',
      category: 'ACTION',
      eventType: 'ACTION',
      details: `[G22_SUTRADARA_AJAIB_VERIFIED] Sutradara Config Updated: ${JSON.stringify(partial)}`,
      route: '/director/settings',
      severity: 'INFO'
    });
  }

  /**
   * P7: Sutradara Harian Otomatis
   * Checks daily schedule and composes 1 episode per day deterministically
   */
  public checkDailyAutoGeneration() {
    if (!this.config.dailyAutoDirectorEnabled) return;

    const todayStr = new Date().toISOString().slice(0, 10);
    if (this.config.lastDailyDateStr === todayStr) return;

    // Pick rotating theme based on Day of Week
    const themesList: DirectorTheme[] = [
      'PPDB', 'TRANSPORTASI', 'PERSAHABATAN', 'ALAM', 'ADAB', 'HEWAN', 'RAMADHAN'
    ];
    const dayIndex = new Date().getDay(); // 0-6
    const selectedTheme = themesList[dayIndex % themesList.length];

    const dailyEp = this.composeEpisode(selectedTheme, {
      titleOverride: `Kisah Harian Sahabat (${new Date().toLocaleDateString('id-ID', { weekday: 'long', day: 'numeric', month: 'long' })})`,
      isDaily: true
    });

    this.episodes = [dailyEp, ...this.episodes.slice(0, 39)];
    this.config.lastDailyDateStr = todayStr;
    this.saveToStorage();
    this.notifyListeners();
    this.notifyConfigListeners();

    blackBoxRecorder.record({
      moduleCode: 'SUTRADARA_HARIAN',
      role: 'SYSTEM',
      tenant: 'TK_ASY_SYIFA',
      category: 'ACTION',
      eventType: 'ACTION',
      details: `[G22_SUTRADARA_AJAIB_VERIFIED] Sutradara Harian Otomatis Berjalan: Episode "${dailyEp.title}" dibuat untuk tanggal ${todayStr}.`,
      route: '/director/daily',
      severity: 'INFO'
    });
  }

  /**
   * Play / Preview Episode Frame Sound
   */
  public playFrameSound(frame: DirectorSceneFrame) {
    asySyifaDnaEngine.playSignatureSound(frame.soundFx);
  }

  public subscribe(cb: (episodes: DirectedEpisode[]) => void): () => void {
    this.listeners.push(cb);
    return () => {
      this.listeners = this.listeners.filter(l => l !== cb);
    };
  }

  public subscribeConfig(cb: (config: DirectorConfig) => void): () => void {
    this.configListeners.push(cb);
    return () => {
      this.configListeners = this.configListeners.filter(l => l !== cb);
    };
  }

  private notifyListeners() {
    this.listeners.forEach(cb => cb([...this.episodes]));
  }

  private notifyConfigListeners() {
    this.configListeners.forEach(cb => cb({ ...this.config }));
  }
}

export const sutradaraAjaibEngine = new SutradaraAjaibEngine();
