import React, { useState } from 'react';
import {
  Globe,
  Lock,
  Search,
  FileCode,
  CheckCircle2,
  ExternalLink,
  ShieldCheck,
  Server,
  Layers,
  Sparkles,
  Download,
  Copy,
  Check
} from 'lucide-react';
import { blackBoxRecorder } from '../../services/blackBoxRecorder';

export const SchoolDeploymentBridge: React.FC = () => {
  const [copiedRobots, setCopiedRobots] = useState<boolean>(false);
  const [copiedSitemap, setCopiedSitemap] = useState<boolean>(false);

  const robotsTxtContent = `# ==========================================
# ROBOTS.TXT — KB-TK-TPA SENTRA ASY-SYIFA TANGGUL
# Generated by TADE RC57 School Deployment Constitution
# ==========================================

User-agent: *
Allow: /
Allow: /ppdb
Allow: /berita
Allow: /galeri
Allow: /profil
Allow: /kurikulum-sentra
Allow: /kontak

# Disallow indexing on private management portal
Disallow: /app/
Disallow: /sim/
Disallow: /admin/
Disallow: /api/
Disallow: /keuangan/
Disallow: /arsip/
Disallow: /raport/

Sitemap: https://asy-syifa.sch.id/sitemap.xml
`;

  const sitemapXmlContent = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>https://asy-syifa.sch.id/</loc>
    <lastmod>2026-08-16</lastmod>
    <changefreq>daily</changefreq>
    <priority>1.0</priority>
  </url>
  <url>
    <loc>https://asy-syifa.sch.id/ppdb</loc>
    <lastmod>2026-08-16</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.9</priority>
  </url>
  <url>
    <loc>https://asy-syifa.sch.id/berita</loc>
    <lastmod>2026-08-16</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://asy-syifa.sch.id/kurikulum-sentra</loc>
    <lastmod>2026-08-16</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://asy-syifa.sch.id/profil</loc>
    <lastmod>2026-08-16</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
</urlset>`;

  const copyToClipboard = (text: string, type: 'robots' | 'sitemap') => {
    navigator.clipboard.writeText(text);
    if (type === 'robots') {
      setCopiedRobots(true);
      setTimeout(() => setCopiedRobots(false), 2000);
    } else {
      setCopiedSitemap(true);
      setTimeout(() => setCopiedSitemap(false), 2000);
    }
  };

  return (
    <div id="school-deployment-bridge-root" className="space-y-6 max-w-7xl mx-auto p-4 sm:p-6 pb-24 font-sans">
      {/* Top Header */}
      <div className="bg-slate-900 text-white p-6 rounded-3xl border border-slate-800 shadow-xl relative overflow-hidden">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div>
            <div className="flex items-center gap-2 mb-1">
              <span className="bg-emerald-500/20 text-emerald-300 border border-emerald-500/30 text-[10px] px-2.5 py-0.5 rounded-full font-mono font-bold tracking-wider">
                R394 &bull; SCHOOL DEPLOYMENT CONSTITUTION
              </span>
              <span className="text-xs text-slate-400 font-mono">Clean Domain Segregation &amp; SEO Engine</span>
            </div>
            <h1 className="text-2xl sm:text-3xl font-bold tracking-tight text-white flex items-center gap-3">
              <Globe className="w-8 h-8 text-emerald-400" />
              Pemisahan Domain: Website Publik vs Aplikasi SIM
            </h1>
            <p className="text-xs text-slate-300 mt-1 max-w-2xl">
              Memisahkan secara permanen Website Publik (SEO, Google Index, PPDB, Berita) dari Web App Internal (Login RBAC, SIM, Arsip, Keuangan) dengan generator robots.txt &amp; sitemap.xml otomatis.
            </p>
          </div>

          <div className="flex items-center gap-2">
            <span className="px-3.5 py-2 rounded-2xl bg-emerald-950 border border-emerald-500/40 text-emerald-300 font-mono text-xs font-bold">
              SEO 100% SECURED
            </span>
          </div>
        </div>
      </div>

      {/* Two Pillars: Website vs Web App */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 font-mono text-xs">
        {/* Pillar 1: Website Publik */}
        <div className="p-6 rounded-3xl bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 shadow-sm space-y-4">
          <div className="flex items-center justify-between border-b border-slate-100 dark:border-slate-700 pb-3">
            <div className="flex items-center gap-2">
              <Globe className="w-5 h-5 text-emerald-500" />
              <h3 className="font-bold text-sm text-slate-900 dark:text-white">1. WEBSITE PUBLIK (SEO &amp; CITRA)</h3>
            </div>
            <span className="px-2 py-0.5 rounded bg-emerald-100 dark:bg-emerald-950 text-emerald-800 dark:text-emerald-300 font-bold text-[10px]">
              PUBLIC INDEXABLE
            </span>
          </div>

          <p className="text-slate-500 dark:text-slate-400 text-[11px] leading-relaxed">
            Dikhususkan untuk mesin pencari Google, wali santri luar, dan calon pendaftar santri baru.
          </p>

          <div className="space-y-2 text-[11px]">
            <div className="p-2.5 rounded-xl bg-slate-50 dark:bg-slate-700/30 border border-slate-200 dark:border-slate-700 flex justify-between">
              <span>Halaman Utama &amp; Profil:</span>
              <strong className="text-emerald-600 dark:text-emerald-400">https://asy-syifa.sch.id/</strong>
            </div>
            <div className="p-2.5 rounded-xl bg-slate-50 dark:bg-slate-700/30 border border-slate-200 dark:border-slate-700 flex justify-between">
              <span>Portal PPDB Online:</span>
              <strong className="text-emerald-600 dark:text-emerald-400">/ppdb</strong>
            </div>
            <div className="p-2.5 rounded-xl bg-slate-50 dark:bg-slate-700/30 border border-slate-200 dark:border-slate-700 flex justify-between">
              <span>Berita &amp; Artikel Sentra:</span>
              <strong className="text-emerald-600 dark:text-emerald-400">/berita</strong>
            </div>
          </div>
        </div>

        {/* Pillar 2: Web App SIM */}
        <div className="p-6 rounded-3xl bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 shadow-sm space-y-4">
          <div className="flex items-center justify-between border-b border-slate-100 dark:border-slate-700 pb-3">
            <div className="flex items-center gap-2">
              <Lock className="w-5 h-5 text-purple-500" />
              <h3 className="font-bold text-sm text-slate-900 dark:text-white">2. WEB APP INTERNAL (SIM &amp; DATA)</h3>
            </div>
            <span className="px-2 py-0.5 rounded bg-purple-100 dark:bg-purple-950 text-purple-800 dark:text-purple-300 font-bold text-[10px]">
              RBAC PROTECTED
            </span>
          </div>

          <p className="text-slate-500 dark:text-slate-400 text-[11px] leading-relaxed">
            Dikhususkan untuk Guru, Yayasan, Kepala Sekolah, Keuangan, dan Pengawas Keamanan.
          </p>

          <div className="space-y-2 text-[11px]">
            <div className="p-2.5 rounded-xl bg-slate-50 dark:bg-slate-700/30 border border-slate-200 dark:border-slate-700 flex justify-between">
              <span>Autentikasi &amp; Login:</span>
              <strong className="text-purple-600 dark:text-purple-400">PIN / QR / Passkey</strong>
            </div>
            <div className="p-2.5 rounded-xl bg-slate-50 dark:bg-slate-700/30 border border-slate-200 dark:border-slate-700 flex justify-between">
              <span>Sistem Kas &amp; Tagihan:</span>
              <strong className="text-purple-600 dark:text-purple-400">Banking Grade Formula</strong>
            </div>
            <div className="p-2.5 rounded-xl bg-slate-50 dark:bg-slate-700/30 border border-slate-200 dark:border-slate-700 flex justify-between">
              <span>Tata Kelola Arsip &amp; Piagam:</span>
              <strong className="text-purple-600 dark:text-purple-400">WORM Storage</strong>
            </div>
          </div>
        </div>
      </div>

      {/* Generated Code Previews: robots.txt & sitemap.xml */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 font-mono text-xs">
        {/* robots.txt */}
        <div className="p-5 rounded-3xl bg-slate-950 text-slate-200 border border-slate-800 shadow-md space-y-3">
          <div className="flex items-center justify-between border-b border-slate-800 pb-2">
            <span className="font-bold text-emerald-400">robots.txt (Otomatis Terbit)</span>
            <button
              onClick={() => copyToClipboard(robotsTxtContent, 'robots')}
              className="px-2.5 py-1 rounded-lg bg-slate-800 hover:bg-slate-700 text-white text-[10px] flex items-center gap-1"
            >
              {copiedRobots ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              {copiedRobots ? 'Tersalin' : 'Salin'}
            </button>
          </div>
          <pre className="text-[10px] text-slate-400 overflow-x-auto p-2 bg-black/40 rounded-xl max-h-48">
            {robotsTxtContent}
          </pre>
        </div>

        {/* sitemap.xml */}
        <div className="p-5 rounded-3xl bg-slate-950 text-slate-200 border border-slate-800 shadow-md space-y-3">
          <div className="flex items-center justify-between border-b border-slate-800 pb-2">
            <span className="font-bold text-cyan-400">sitemap.xml (Otomatis Terbit)</span>
            <button
              onClick={() => copyToClipboard(sitemapXmlContent, 'sitemap')}
              className="px-2.5 py-1 rounded-lg bg-slate-800 hover:bg-slate-700 text-white text-[10px] flex items-center gap-1"
            >
              {copiedSitemap ? <Check className="w-3.5 h-3.5 text-cyan-400" /> : <Copy className="w-3.5 h-3.5" />}
              {copiedSitemap ? 'Tersalin' : 'Salin'}
            </button>
          </div>
          <pre className="text-[10px] text-slate-400 overflow-x-auto p-2 bg-black/40 rounded-xl max-h-48">
            {sitemapXmlContent}
          </pre>
        </div>
      </div>
    </div>
  );
};
